---
title: "Serological investigation of Lassa mammarenavirus among rodent species in Eastern Sierra Leone."
author:
  - name: "David Simons"
    url: https://github.com/diddrog11/rodent_trapping
    affiliation: The Royal Veterinary College, London, UK
    affiliation_url: https://www.rvc.ac.uk
    orcid_id: 0000-0001-9655-1656
date: "`r Sys.Date()`"
output:
  # distill::distill_article:
  #   self_contained: false
  #   toc: true
   html_document
  # word_document
bibliography: citations.bib
categories:
  - Lassa
---

```{r setup, include=FALSE, quietly=TRUE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
library(here)
```

# Abstract

# Introduction

Lassa fever caused by *Lassa mammarenavirus* is an endemic zoonotic disease with an between 100,000-900,000 annual infections [@mccormick_prospective_1987; @basinski_bridging_2021]. Asymptomatic infection is thought to be common (up to 80%), although individuals with severe symptoms requiring hospitalisation have generally poor outcomes with mortality in this group reported as 15%. The majority of annually reported cases come from Nigeria, where the Nigerian Centre for Disease Control have rapidly expanded access to testing and centralised reporting of Lassa fever cases. Cases are also reported from the Mano River Valley countries of Guinea, Liberia and Sierra Leone, where testing is less available and reporting more sporadic. Within the countries reporting Lassa fever cases there is important spatial clustering of cases, typically from rural areas. Lassa fever outbreaks also demonstrate temporal variability. In Nigeria reported cases peak in the first 3 months of the year, with low numbers of cases reported throughout the remaining periods, these patterns are less clear in the Western endemic countries with no consistent temporal association with a peak in reported cases.

Human infections are associated with spillover from rodent hosts, with limited human-to-human transmission reported. The primary host is *Mastomys natalensis* a commensal, native, rodent species present throughout sub-Saharan Africa. These rodents do not develop any clinical symptoms following infection with *Lassa mammarenavirus* and are susceptible to low infectious doses consistent with what might be obtained from a wound from an infected conspecific [safronetz, 2022]. Viral RNA is detectable 3 days postinfection, peaking within 1 to 2 weeks and resolving within approximately 40 days, however, RNA persistance was observed in testes beyond this point, prolonged sexual transmission may therefore exist. Based on a similar arenavirus (Morogoro virus), seroconversion is expected to occur 7 days post infection, with detectable antibodies remaining beyond the point in which circulating RNA has declined, therefore seroprevalence is a useful measure of pathogen existence within a location. Transmission, between individuals was found to occur through both contaminated fomites and direct contact, presenting two methods driving sustained pathogen transmission in endemic areas.

Despite *M. natalensis* being identified as the primary reservoir, 13 other rodent species have been identified to be acutely or previously infected with *Lassa mammarenavirus* in the endemic zone. The contribution of these species to pathogen spillover, viral transmission and maintenance is unknown. The high contact rates between rodents in species rich environments may produce incidental infections of non-reservoir species which subsequently get detect through surveillance activities while having little impact on viral transmission. Alternatively, these species may act to transfer this pathogen spatially and link *M. natalensis* populations that would not come into contact otherwise. It is therefore important to characterise rodent networks within endemic settings, rather than limiting investigation to a single rodent population.

The composition of rodent networks and the interaction between different rodent species in Lassa fever endemic regions has not been systematically reported. Previous studies have limited description of the wider rodent populations to measures of species richness and diversity. Additional information on the temporal and spatial overlap of individuals to infer potential for contact between individuals and importantly the risk of transmission of zoonotic pathogens, including *Lassa mammarenavirus*, is important. Pathogens typically persist in dense, well-connected networks. In discontinuous networks, pathogens with limited environmental transmission will die out as the number of susceptible individuals is rapidly depleted. We hypothesise that rodent contact rates would be greater in peri-urban settings where nutritional resources are more concentrated than in less anthropogenically modified landuse types. We further hypothesise that commensal rodent species, including *M. natalensis*, will have higher contact rates than non-commensal species such as *Praomys spp.*. It is expected that rodents with high connectivity to other individuals will be associated with antibody positivity for *Lassa mammarenavirus*.

Here, we report potential contact networks of rodents in a Lassa fever endemic region, we analyse these networks to identify the rate of contact between rodents in different landuse settings. We report the prevalence of antibodies against *Lassa mammarenavirus* among rodents the region and explore the contact networks of positive rodents by landuse settings. 
  
# Methods

## Study area

We conducted rodent trapping at 7 trapping sites within 5 villages in the Lassa fever endemic zone of the Eastern Province of Sierra Leone. We surveyed the rodent community in forested, fallow, agricultural and areas of human occupation (within and outside of homes) along an anthropogenic land use gradient. Current land-use was classified at the level of trapping site as Agriculture, Fallow-land and Forested. Traps placed within villages were further defined as being within human dwellings (Village inside) and outside of permanent structures (Village outside). The village sites were enrolled based on accessibility to the sites during all seasons, discussions with the Lassa fever outreach team at Kenema Government Hospital and acceptability of the protocol to the village community. Villages and trapping sites were selected to be representative at the study level for land use in Eastern Sierra Leone. One of the villages, Bambawo, was only included for a single visit.

Trap sites were geo-located for repeated trapping activities, changes to land-use at the trapping site were recorded at each visit. Within each study site 49 individual Sherman traps (**size and reference**) were baited with a locally produced mixture of oats, palm oil and dried fish for 4 consecutive nights. Each morning the traps were checked and closed for the day prior to re-baiting during the evening.

## Rodent samples

Trapped rodents were sedated with halothane and euthanised prior to obtaining morphological measurements and samples of blood and tissue (**reference to RVC and local ethics approval**) following published guidance [@fichet-calvet_chapter_2014]. Rodents were sexed based on external and internal genitalia. Age estimation was performed through description of the rodents reproductive status (identification of perforate or imperforate vagina, scarring from prior embryo development, current pregnancy status or descent of testes and seminal vesicle development) and weighing of dried eye lenses. Carcasses were disposed and processed in the field to eliminate risk of pathogen transmission.

Molecular identification to species was performed on dried blood spots that were stored at -20°C until processing. Genomic DNA was extracted using QIAGEN DNAeasy kits as per the manufacturers instructions [ref]. DNA extracts were amplified using platinum *Taq* polymerase (Invitrogen) and cytochrome B primers. DNA amplification was assessed through gel electrophoreisis with successful amplification products undergoing Sanger sequencing. Obtained sequences were compared using BLAST against NCBI records for rodent cytochrome B.

## Do rodent contact rates differ by landuse type?

To understand potential contact between individual small mammal species we produce a buffer zone, with a radius of 50m, around each trapped individual. The `sf` package in the R statistical computing language was used for geospatial manipulation and analysis with the `igraph` package used to produce the rodent networks [@pebesma_simple_2018; @r_core_team_r_2021]. To test whether rodent contact rates vary by landuse type we analyse the composition of these networks comparing edge density, betweenness and .... Within these networks we further explore species level measures of degree, closeness and betweenness.

## *Lassa mammarenavirus* serology

The ELISA was performed using the BLACKBOX® LASV IgG ELISA Kit developed by the Diagnostics Development Laboratory hosted at the Bernhard Nocht Institute for Tropical Medicine [ref]. The protocol is available as Supplementary Material 1. Briefly, 1 µL of whole blood was inactivated by mixing with the provided sample dilution buffer (1:50). Where whole blood was unavailable, blood was extracted from dried blood spots stored on filter paper by incubating with phosphate-buffered saline containing 0.08% Sodium Azide and 0.05% Tween 20. Samples and negative and positive controls were incubated on the provided ELISA plate for 24 hours at 4–8 °C in a wet chamber. Following incubation, the plates were washed with subsequent incubation for one hour with 1:10,000 diluted HRP-labelled streptavidin. A final wash was performed before the addition of 100 µL of 3,3’,5,5’-Tetramethylbenzidine (TMB) substrate to all the wells, with incubation for 10 min. The colorimetric reaction was stopped by adding 100µL of a stop solution.

In a deviation from the kit description the optical density (OD) at 450nm and 630nm was measured (as opposed to 450nm and 620nm). The index value was produced from the OD difference (OD_450_ - OD_630_) divided by the cut-off values (the mean values of the negative controls + 0.150). Samples were considered positive with index values greater or equal to 1.1, negative results less than or equal to 0.9, and inconclusive results when the index value lay between 0.9 and 1.1. Inconclusive results were repeated as advised by the kit manufacturers.

## What is the prevalence of antibodies to *Lassa mammarenavirus* in an endemic setting in Sierra Leone?

We report the prevalence of antibodies to *Lassa mammarenavirus* in our trapped population. We explore how this varies between village study site, landuse type and species of rodent. To understand any fluctuation in prevalence we report on the temporal variation of seroprevalence in trapped rodents.

## Are *Lassa mammarenavirus* exposed rodents members of highly connected networks?

The networks produced for each landuse category were further subset to only include contacts between antibody positive individuals other co-located individuals. These sub-graphs were analysed using the same metrics as for the landuse graphs.

# Results

During the study 420 individual rodents were trapped from 26,524 trap-nights (TN). We identified 12 species from molecular classification, the majority of individuals were identified as *M. natalensis* (N = 75, 17.9%), *Lophuromys sikapusi* (N = 44, 10.5%) and *Mus musculus* (N = 41, 9.8%) (Table 1.). 

Antibodies to *Lassa mammarenavirus* were identified in 20 (4.4%) rodents, including 7 *M. natalensis* (35%), 5 *Crocidura spp.* (25%), 3 *L. sikapusi* (15%) and 3 *Mus minutoides* (15%) (Table 1.). The highest proportion of positivity by the number of individuals tested from a species was observed in *Malacomys edwardsii* (N = 1, 12.5%), *M. natalensis* (N = 7, 9.3%) and *Mus minutoides* (N = 3, 8.6%). 

Rodents with antibodies to *Lassa mammarenavirus* were detected in three of the villages, Lalehun (N = 11, 55%), Seilama (N = 8, 40%) and Baiama (N = 1, 5%) (Supplementary Table 1.). No positive rodents were detected in Lambayama or Bambawo. Among the villages with positive rodents the highest rates of positivity among trapped rodents was from Lalehun (10.1%), followed by Seilama (4.2%) and Baiama (2.2%). Positive rodents were detected during all study visits, the highest rate of positivity was observed during trapping conducted in June (N = 5, 8.6%), the lowest positivity rate was observed in November (N = 1, 2.2%) (Supplementary Table 2.). Most antibody positive rodents were trapped in agricultural settings (N = 13, 65%), followed by peri-urban (N = 6, 30%) and forest settings (N = 1, 5%). The rate of positivity was similar in both village and agricultural settings (4.9%) and lower in forest habitats (3.2%). 

# Discussion

Future work should include testing these samples for acute viral infection using RT-PCR to understand the risk of viral transmission to humans.

# Conclusion

# References
